### ISSUE TITLE
Bundle cannot find mongoid version 2.0.0.beta11

### ISSUE THREAD

**Issue by pablomartinez** [fortuity/rails3-mongoid-devise#1]
It looks like in the Gemfile the version for mongoid should be = 2.0.0.beta.11 (with a dot between beta and 11)

**Comment by pablomartinez** [comment]
This has been solved with the latest commit (2.0.0.beta.15)

**Comment by fortuity** [comment]
And I've updated the rails3-mongoid-devise repository to use 2.0.0.beta.15.
