### ISSUE TITLE
With MongoHQ, exception: can't drop system ns

### ISSUE THREAD

**Issue by turadg** [fortuity/rails3-mongoid-devise#10]
Thanks for this tutorial. After following it with a local MongoDB, I tried it with Heroku and MongoHQ but I ran into this error on `heroku rake db:seed`:

rake aborted!
Database command 'drop' failed: {"ns"=>"first.system.users", "errmsg"=>"exception: can't drop system ns", "code"=>12502, "ok"=>0.0}

(See full trace by running task with --trace)
(in /disk1/home/slugs/387956_f14071c_5baa-49f7813f-602e-4ef4-acce-cd70e881a279/mnt)
EMPTY THE MONGODB DATABASE

My local Mongo has just system.indexes but the MongoHQ db has system.users too. I tried adding a check in seeds.rb but it didn't help:

Mongoid.master.collections.reject { |c| c.name == 'system.indexes' || c.name == 'system.users'}.each(&:drop)

Not sure if it matters, but these are my gem versions (which are newer than in the tutorial):

gem 'mongoid', '2.0.0.beta.20'
gem 'bson_ext', '1.1.5'
gem 'devise', '1.1.5'
gem 'heroku', '1.15.1'

**Comment by fortuity** [comment]
Please try this and tell me if it resolves the issue:

```
Mongoid.master.collections.reject { |c| c.name =~ /^system/}.each(&:drop)
```

Thanks,
Daniel

**Comment by turadg** [comment]
Yep! Though shouldn't that regexp include the namespace dot? I.e. 
/^system./ so a user table 'systematic' would still be dropped.

I don't know why the renderer is superscripting that but I simply added a . after system.

**Comment by fortuity** [comment]
Ok, thanks, I'll update the app.

The superscripting here results from the markup engine. You can indent four spaces and it'll render as code.
