### ISSUE TITLE
Permission denied (publickey). when doing git clone git@github.com:fortuity/rails3-mongoid-devise.git

### ISSUE THREAD

**Issue by mrichman** [fortuity/rails3-mongoid-devise#11]
<pre>
mark@macpro:rails# git clone git@github.com:fortuity/rails3-mongoid-devise.git
Initialized empty Git repository in /Users/mark/Sites/rails/rails3-mongoid-devise/.git/
Warning: Permanently added the RSA host key for IP address '207.97.227.239' to the list of known hosts.
Permission denied (publickey).
fatal: The remote end hung up unexpectedly

**Comment by fortuity** [comment]
Thanks for alerting me to this error in the documentation. I had provided the "read/write" link where the "read only" link is correct. Try

<pre>
git clone git://github.com/fortuity/rails3-mongoid-devise.git
</pre>


I've updated the documentation to correct this.
