### ISSUE TITLE
Need to update rails3-application-templates

### ISSUE THREAD

**Issue by danhealy** [fortuity/rails3-mongoid-devise#16]
I just ran through the process of using this template with:

```
rails new app_name -m https://github.com/fortuity/rails3-application-templates/raw/master/rails3-mongoid-devise-template.rb
```

and encountered the problem that was fixed by

https://github.com/fortuity/rails3-mongoid-devise/commit/2d719f569e0eb0e8757ece60a8fc8ef48ddf39c8

Just thought I should let you know..  (thanks for the amazing template by the way)

--Dan

**Comment by fortuity** [comment]
Hi Dan,

I've made extensive changes to the application template. Please try generating the app again and let me know if the problem is resolved.

Thanks!

-- Daniel

**Comment by danhealy** [comment]
Just now ran through it again.
    ruby-1.9.2-p136@sandbox @/sandbox [09:30:53] :) $ rails new template_test -m https://github.com/fortuity/rails3-application-templates/raw/master/rails3-mongoid-devise-template.rb
          create  
          create  README
          create  Rakefile
          create  config.ru
          create  .gitignore
          create  Gemfile
          create  app
          create  app/controllers/application_controller.rb
          create  app/helpers/application_helper.rb
          create  app/mailers
          create  app/models
          create  app/views/layouts/application.html.erb
          create  config
          create  config/routes.rb
          create  config/application.rb
          create  config/environment.rb
          create  config/environments
          create  config/environments/development.rb
          create  config/environments/production.rb
          create  config/environments/test.rb
          create  config/initializers
          create  config/initializers/backtrace_silencers.rb
          create  config/initializers/inflections.rb
          create  config/initializers/mime_types.rb
          create  config/initializers/secret_token.rb
          create  config/initializers/session_store.rb
          create  config/locales
          create  config/locales/en.yml
          create  config/boot.rb
          create  config/database.yml
          create  db
          create  db/seeds.rb
          create  doc
          create  doc/README_FOR_APP
          create  lib
          create  lib/tasks
          create  lib/tasks/.gitkeep
          create  log
          create  log/server.log
          create  log/production.log
          create  log/development.log
          create  log/test.log
          create  public
          create  public/404.html
          create  public/422.html
          create  public/500.html
          create  public/favicon.ico
          create  public/index.html
          create  public/robots.txt
          create  public/images
          create  public/images/rails.png
          create  public/stylesheets
          create  public/stylesheets/.gitkeep
          create  public/javascripts
          create  public/javascripts/application.js
          create  public/javascripts/controls.js
          create  public/javascripts/dragdrop.js
          create  public/javascripts/effects.js
          create  public/javascripts/prototype.js
          create  public/javascripts/rails.js
          create  script
          create  script/rails
          create  test
          create  test/fixtures
          create  test/functional
          create  test/integration
          create  test/performance/browsing_test.rb
          create  test/test_helper.rb
          create  test/unit
          create  tmp
          create  tmp/sessions
          create  tmp/sockets
          create  tmp/cache
          create  tmp/pids
          create  vendor/plugins
          create  vendor/plugins/.gitkeep
           apply  https://github.com/fortuity/rails3-application-templates/raw/master/rails3-mongoid-devise-template.rb
          wizard    Modifying a new Rails app to use Mongoid and Devise...
          wizard    Any problems? See http://github.com/fortuity/rails3-mongoid-devise/issues
      Would you like to use RSpec instead of TestUnit? (yes/no) yes
      Would you like to use Cucumber for your BDD? (yes/no) no 
      Would you like to use jQuery instead of Prototype? (yes/no) yes
      Would you like to use the Haml template system? (yes/no) yes
      Do you want to install the Heroku gem so you can deploy to Heroku? (yes/no) yes
      Would you like to use Yard instead of RDoc? (yes/no) no
          recipe    Running Git recipe...
          remove    .gitignore
          create    .gitignore
             run    git init from "."
    Initialized empty Git repository in /sandbox/template_test/.git/
             run    git add . from "."
             run    git commit -aqm 'Initial commit of new Rails app' from "."
          wizard    Creating a git working_branch (to follow the stream of development).
             run    git checkout  -b working_branch from "."
    Switched to a new branch 'working_branch'
             run    git add . from "."
             run    git commit -m 'Initial commit of working_branch (to establish a clean base line).' from "."
    # On branch working_branch
    nothing to commit (working directory clean)
          recipe    Running Mongoid recipe...
         gemfile    mongoid (>= 2.0.0.rc.7)
         gemfile    bson_ext (>= 1.2.4)
          remove    config/database.yml
             run    git tag mongoid_installation from "."
             run    git add . from "."
             run    git commit -am 'Mongoid installation.' from "."
    [working_branch 60a6aa3] Mongoid installation.
     2 files changed, 5 insertions(+), 0 deletions(-)
          recipe    Running jQuery recipe...
          remove    public/javascripts/rails.js
          create    public/javascripts/rails.js
          create    public/javascripts/jquery.js
            gsub    config/application.rb
             run    git tag jquery_installation from "."
             run    git add . from "."
             run    git commit -am 'jQuery installation.' from "."
    [working_branch 431628a] jQuery installation.
     2 files changed, 173 insertions(+), 191 deletions(-)
     create mode 100644 public/javascripts/jquery.js
     rewrite public/javascripts/rails.js (99%)
          recipe    Running HAML recipe...
         gemfile    haml (>= 3.0.0)
         gemfile    haml-rails
             run    git tag haml_installation from "."
             run    git add . from "."
             run    git commit -am 'Haml installation.' from "."
    [working_branch 773f2e9] Haml installation.
     1 files changed, 2 insertions(+), 0 deletions(-)
          recipe    Running RSpec recipe...
         gemfile    rspec-rails (>= 2.5)
         gemfile    database_cleaner
          recipe    Running ActionMailer configuration recipe...
            gsub    config/environments/development.rb
            gsub    config/environments/development.rb
            gsub    config/environments/production.rb
             run    git tag ActionMailer_config from "."
             run    git add . from "."
             run    git commit -am 'Set ActionMailer configuration.' from "."
    [working_branch ee38049] Set ActionMailer configuration.
     3 files changed, 19 insertions(+), 2 deletions(-)
          recipe    Running Devise recipe...
         gemfile    devise (>= 1.2.rc)
          recipe    Running add_user_name recipe...
         gemfile    hpricot
         gemfile    ruby_parser
          recipe    Running Home Page recipe...
          recipe    Running Home Page Showing Users recipe...
          recipe    Running Seed Database recipe...
          recipe    Running Users Page recipe...
          recipe    Running CSS Setup recipe...
          recipe    Running Application Layout recipe...
          recipe    Running Devise Navigation recipe...
          recipe    Running cleanup recipe...
          remove    README
          remove    doc/README_FOR_APP
          remove    public/index.html
          remove    public/images/rails.png
          create    README
          create    README.textile
            gsub    README
            gsub    README.textile
            gsub    Gemfile
            gsub    Gemfile
             run    git tag file_cleanup from "."
             run    git add . from "."
             run    git commit -am 'Removed unnecessary files left over from initial app generation.' from "."
    [working_branch 8f6cc5c] Removed unnecessary files left over from initial app generation.
     6 files changed, 79 insertions(+), 534 deletions(-)
     rewrite Gemfile (71%)
     rewrite README (99%)
     create mode 100644 README.textile
     delete mode 100644 doc/README_FOR_APP
     delete mode 100644 public/images/rails.png
     delete mode 100644 public/index.html
          recipe    Running ban spiders recipe...
          wizard    banning spiders from your site by changing robots.txt
            gsub    public/robots.txt
            gsub    public/robots.txt
             run    git tag ban_spiders from "."
             run    git add . from "."
             run    git commit -am 'Ban spiders from the site by changing robots.txt' from "."
    [working_branch c501916] Ban spiders from the site by changing robots.txt
     1 files changed, 2 insertions(+), 2 deletions(-)
          wizard    Running Bundler install. This will take a while.
             run    bundle install from "."
    Fetching source index for http://rubygems.org/
    Using rake (0.8.7) 
    Using abstract (1.0.0) 
    Using activesupport (3.0.4) 
    Using builder (2.1.2) 
    Using i18n (0.5.0) 
    Using activemodel (3.0.4) 
    Using erubis (2.6.6) 
    Using rack (1.2.1) 
    Using rack-mount (0.6.13) 
    Using rack-test (0.5.7) 
    Using tzinfo (0.3.24) 
    Using actionpack (3.0.4) 
    Using mime-types (1.16) 
    Using polyglot (0.3.1) 
    Using treetop (1.4.9) 
    Using mail (2.2.15) 
    Using actionmailer (3.0.4) 
    Installing arel (2.0.9) 
    Using activerecord (3.0.4) 
    Using activeresource (3.0.4) 
    Using bcrypt-ruby (2.1.4) 
    Installing bson (1.2.4) 
    Installing bson_ext (1.2.4) with native extensions 
    Using bundler (1.0.10) 
    Installing database_cleaner (0.6.4) 
    Using orm_adapter (0.0.4) 
    Using warden (1.0.3) 
    Using devise (1.2.rc) 
    Installing diff-lcs (1.1.2) 
    Using haml (3.0.25) 
    Using thor (0.14.6) 
    Using railties (3.0.4) 
    Using haml-rails (0.3.4) 
    Installing hpricot (0.8.4) with native extensions 
    Installing mongo (1.2.4) 
    Using will_paginate (3.0.pre2) 
    Using mongoid (2.0.0.rc.7) 
    Using rails (3.0.4) 
    Installing rspec-core (2.5.1) 
    Installing rspec-expectations (2.5.0) 
    Installing rspec-mocks (2.5.0) 
    Installing rspec (2.5.0) 
    Installing rspec-rails (2.5.0) 
    Using sexp_processor (3.0.5) 
    Installing ruby_parser (2.0.6) 
    Using sqlite3 (1.3.3) 
    Your bundle is complete! Use `bundle show [gemname]` to see where a bundled gem is installed.
          wizard    Running after Bundler callbacks.
        generate    mongoid:config
    /Users/danhealy/.rvm/gems/ruby-1.9.2-p136@sandbox/gems/railties-3.0.4/lib/rails/application/configuration.rb:88:in `read': No such file or directory - /sandbox/template_test/config/database.yml (Errno::ENOENT)
        from /Users/danhealy/.rvm/gems/ruby-1.9.2-p136@sandbox/gems/railties-3.0.4/lib/rails/application/configuration.rb:88:in`database_configuration'
        from /Users/danhealy/.rvm/gems/ruby-1.9.2-p136@sandbox/gems/activerecord-3.0.4/lib/active_record/railtie.rb:58:in `block (2 levels) in <class:Railtie>'
        from /Users/danhealy/.rvm/gems/ruby-1.9.2-p136@sandbox/gems/activesupport-3.0.4/lib/active_support/lazy_load_hooks.rb:36:in`instance_eval'
        from /Users/danhealy/.rvm/gems/ruby-1.9.2-p136@sandbox/gems/activesupport-3.0.4/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
        from /Users/danhealy/.rvm/gems/ruby-1.9.2-p136@sandbox/gems/activesupport-3.0.4/lib/active_support/lazy_load_hooks.rb:26:in`on_load'
        from /Users/danhealy/.rvm/gems/ruby-1.9.2-p136@sandbox/gems/activerecord-3.0.4/lib/active_record/railtie.rb:57:in `block in <class:Railtie>'
        from /Users/danhealy/.rvm/gems/ruby-1.9.2-p136@sandbox/gems/railties-3.0.4/lib/rails/initializable.rb:25:in`instance_exec'
        from /Users/danhealy/.rvm/gems/ruby-1.9.2-p136@sandbox/gems/railties-3.0.4/lib/rails/initializable.rb:25:in `run'
        from /Users/danhealy/.rvm/gems/ruby-1.9.2-p136@sandbox/gems/railties-3.0.4/lib/rails/initializable.rb:50:in`block in run_initializers'
        from /Users/danhealy/.rvm/gems/ruby-1.9.2-p136@sandbox/gems/railties-3.0.4/lib/rails/initializable.rb:49:in `each'
        from /Users/danhealy/.rvm/gems/ruby-1.9.2-p136@sandbox/gems/railties-3.0.4/lib/rails/initializable.rb:49:in`run_initializers'
        from /Users/danhealy/.rvm/gems/ruby-1.9.2-p136@sandbox/gems/railties-3.0.4/lib/rails/application.rb:134:in `initialize!'
        from /Users/danhealy/.rvm/gems/ruby-1.9.2-p136@sandbox/gems/railties-3.0.4/lib/rails/application.rb:77:in`method_missing'
        from /sandbox/template_test/config/environment.rb:8:in `<top (required)>'
        from /Users/danhealy/.rvm/gems/ruby-1.9.2-p136@sandbox/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:239:in`require'
        from /Users/danhealy/.rvm/gems/ruby-1.9.2-p136@sandbox/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:239:in `block in require'
        from /Users/danhealy/.rvm/gems/ruby-1.9.2-p136@sandbox/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:225:in`block in load_dependency'
        from /Users/danhealy/.rvm/gems/ruby-1.9.2-p136@sandbox/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:596:in `new_constants_in'
        from /Users/danhealy/.rvm/gems/ruby-1.9.2-p136@sandbox/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:225:in`load_dependency'
        from /Users/danhealy/.rvm/gems/ruby-1.9.2-p136@sandbox/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:239:in `require'
        from /Users/danhealy/.rvm/gems/ruby-1.9.2-p136@sandbox/gems/railties-3.0.4/lib/rails/application.rb:103:in`require_environment!'
        from /Users/danhealy/.rvm/gems/ruby-1.9.2-p136@sandbox/gems/railties-3.0.4/lib/rails/commands.rb:16:in `<top (required)>'
        from script/rails:6:in`require'
        from script/rails:6:in `<main>'
        generate    rspec:install
    /Users/danhealy/.rvm/gems/ruby-1.9.2-p136@sandbox/gems/railties-3.0.4/lib/rails/application/configuration.rb:88:in`read': No such file or directory - /sandbox/template_test/config/database.yml (Errno::ENOENT)
        from /Users/danhealy/.rvm/gems/ruby-1.9.2-p136@sandbox/gems/railties-3.0.4/lib/rails/application/configuration.rb:88:in `database_configuration'
        from /Users/danhealy/.rvm/gems/ruby-1.9.2-p136@sandbox/gems/activerecord-3.0.4/lib/active_record/railtie.rb:58:in`block (2 levels) in class:Railtie'
        from /Users/danhealy/.rvm/gems/ruby-1.9.2-p136@sandbox/gems/activesupport-3.0.4/lib/active_support/lazy_load_hooks.rb:36:in `instance_eval'
        from /Users/danhealy/.rvm/gems/ruby-1.9.2-p136@sandbox/gems/activesupport-3.0.4/lib/active_support/lazy_load_hooks.rb:36:in`execute_hook'
        from /Users/danhealy/.rvm/gems/ruby-1.9.2-p136@sandbox/gems/activesupport-3.0.4/lib/active_support/lazy_load_hooks.rb:26:in `on_load'
        from /Users/danhealy/.rvm/gems/ruby-1.9.2-p136@sandbox/gems/activerecord-3.0.4/lib/active_record/railtie.rb:57:in`block in class:Railtie'
        from /Users/danhealy/.rvm/gems/ruby-1.9.2-p136@sandbox/gems/railties-3.0.4/lib/rails/initializable.rb:25:in `instance_exec'
        from /Users/danhealy/.rvm/gems/ruby-1.9.2-p136@sandbox/gems/railties-3.0.4/lib/rails/initializable.rb:25:in`run'
        from /Users/danhealy/.rvm/gems/ruby-1.9.2-p136@sandbox/gems/railties-3.0.4/lib/rails/initializable.rb:50:in `block in run_initializers'
        from /Users/danhealy/.rvm/gems/ruby-1.9.2-p136@sandbox/gems/railties-3.0.4/lib/rails/initializable.rb:49:in`each'
        from /Users/danhealy/.rvm/gems/ruby-1.9.2-p136@sandbox/gems/railties-3.0.4/lib/rails/initializable.rb:49:in `run_initializers'
        from /Users/danhealy/.rvm/gems/ruby-1.9.2-p136@sandbox/gems/railties-3.0.4/lib/rails/application.rb:134:in`initialize!'
        from /Users/danhealy/.rvm/gems/ruby-1.9.2-p136@sandbox/gems/railties-3.0.4/lib/rails/application.rb:77:in `method_missing'
        from /sandbox/template_test/config/environment.rb:8:in`<top (required)>'
        from /Users/danhealy/.rvm/gems/ruby-1.9.2-p136@sandbox/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:239:in `require'
        from /Users/danhealy/.rvm/gems/ruby-1.9.2-p136@sandbox/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:239:in`block in require'
        from /Users/danhealy/.rvm/gems/ruby-1.9.2-p136@sandbox/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:225:in `block in load_dependency'
        from /Users/danhealy/.rvm/gems/ruby-1.9.2-p136@sandbox/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:596:in`new_constants_in'
        from /Users/danhealy/.rvm/gems/ruby-1.9.2-p136@sandbox/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:225:in `load_dependency'
        from /Users/danhealy/.rvm/gems/ruby-1.9.2-p136@sandbox/gems/activesupport-3.0.4/lib/active_support/dependencies.rb:239:in`require'
        from /Users/danhealy/.rvm/gems/ruby-1.9.2-p136@sandbox/gems/railties-3.0.4/lib/rails/application.rb:103:in `require_environment!'
        from /Users/danhealy/.rvm/gems/ruby-1.9.2-p136@sandbox/gems/railties-3.0.4/lib/rails/commands.rb:16:in`<top (required)>'
        from script/rails:6:in `require'
        from script/rails:6:in`<main>'
            gsub    spec/spec_helper.rb
    The template [https://github.com/fortuity/rails3-application-templates/raw/master/rails3-mongoid-devise-template.rb] could not be loaded. Error: No such file or directory - /sandbox/template_test/spec/spec_helper.rb

**Comment by fortuity** [comment]
Dan,

Could you please run it again using the "-T -O -J" flags? As in 

<pre>
rails new template_test -m https://github.com/fortuity/rails3-application-templates/raw/master/rails3-mongoid-devise-template.rb -T -O -J
</pre>


We use the -T -O -J flags to skip Test::Unit files, Active Record files, and Prototype files.

Thanks for the follow-through!

-- Daniel

**Comment by danhealy** [comment]
Worked well with those options, and the db/seed issue is gone.  Great work!
