### ISSUE TITLE
Script fails for ruby 1.9.2p180 due to psych yaml parser problem 

### ISSUE THREAD

**Issue by cblock** [fortuity/rails3-mongoid-devise#17]
Script fails validating database name apparently due to a bug in yaml psych parser (which is default in 1.9.2). See http://groups.google.com/group/mongoid/browse_thread/thread/9213a17a73d3c422 and http://redmine.ruby-lang.org/issues/show/4300 for further details. 

Workaround until the next version of ruby is published:

Add after configure section (around line 68):

```
# >------------------------------[ YAML Engine]----------------------------<                                   
inject_into_file 'config/environment.rb', "\nrequire 'yaml'\nYAML::ENGINE.yamler= 'syck'\n", :after => "require File.expand_path('../application', __FILE__)", :verbose => false
```

**Comment by fortuity** [comment]
Carsten,

I've updated the application template and the example app.

Please generate the app from the application template and confirm here whether it works as expected.

I appreciate the contribution.

Thank you!

**Comment by cblock** [comment]
Just tried it out and it works like a charm on my machine. Thanks a lot for the quick fix!

**Comment by fortuity** [comment]
0n 2011-3-27 I removed the workaround added to resolve Issue 17. There should now be no problem using any Rubygems version newer than 1.53 (2011-02-26).

-- Daniel
