### ISSUE TITLE
Default README for Cucumber docs on relishapp

### ISSUE THREAD

**Issue by mattwynne** [fortuity/rails3-mongoid-devise#19]
This should be better documented, but if you rename the file `about_these_examples.md` to `readme.md`, then it will be displayed by default when someone comes to the project's page.

**Comment by fortuity** [comment]
Thanks!

Do you support textile markup? I prefer it to markdown.

Also do you document use of the .nav file? I played with it after seeing it in the VCR project.

-- Daniel

**Comment by mattwynne** [comment]
Hi,

No we only support markdown. I can't see that changing in the foreseeable future as otherwise we'll have to start adding configuration settings etc.

The .nav stuff is somewhat documented in the features (see http://relishapp.com/relish/relish/dir/client-gem/sort-files-and-directories) but TBH relish's features are not a great example of good documentation at the moment.

The .nav file is particular to Relish. David Chelimsky asked for it for RSpec.

**Comment by fortuity** [comment]
Thanks for being so helpful!

-- Daniel
