### ISSUE TITLE
.hamls generated by template.rb cause Haml::SyntaxError

### ISSUE THREAD

**Issue by irohiroki** [fortuity/rails3-mongoid-devise#2]
originally generated .hamls doesn't seem to have a newline character at the end of file and
just append_file'ing app's template ends up making illegal files, like

```
%h1 Home#index
%p Find me in app/views/home/index.html.haml- @users.each do |user|
  %p
    User: #{link_to user.name, user}
```

causing Haml::SyntaxError.

**Comment by fortuity** [comment]
Thanks for alerting me about this issue! I've checked in a corrected file to the repository.

-- Daniel
