### ISSUE TITLE
Can not start server

### ISSUE THREAD

**Issue by stevoyoung** [fortuity/rails3-mongoid-devise#20]
I can't get my rails server to start.

I am on a mac, using a clean install of rails3-mongoid-devise, Rails 3.0.5 and Rudy 1.8.7 patch level 174.

When I try try to start the rails server I get the following message and it never starts.

```
MBP:test-ror stephen$ rails s  
=> Booting WEBrick  
=> Rails 3.0.5 application starting in development on http://0.0.0.0:3000  
=> Call with -d to detach  
=> Ctrl-C to shutdown server  
Exiting  
/Users/Sites/workspace/test-ror/config/environment.rb:4: uninitialized constant YAML::ENGINE (NameError)  
from /Users/Sites/workspace/test-ror/config.ru:3
from /Library/Ruby/Gems/1.8/gems/rack-1.2.2/lib/rack/builder.rb:46:in `instance_eval'
from /Library/Ruby/Gems/1.8/gems/rack-1.2.2/lib/rack/builder.rb:46:in `initialize'
from /Users/stephen/Sites/workspace/atrack-ror/config.ru:1:in `new'
from /Users/Sites/workspace/test-ror/config.ru:1
```

**Comment by stevoyoung** [comment]
It seems as though my problem is in the "enviroment.rb" file. If i remove the follwoing lines it starts:

```
require 'yaml'  
YAML::ENGINE.yamler= 'syck'  
```

Reading the commit for those lines it looks like it was added to fix issues 17. Is there something that I am doing wrong?

https://github.com/fortuity/rails3-mongoid-devise/blob/b8b8d4f0db43a6af2c68f78f223410658fb0526b/config/environment.rb

**Comment by fortuity** [comment]
What version of Rubygems do you have installed?
(check with "gem -v")

Rubygems 1.5.0 changes the yaml parsing default from syck  to psych and psych doesn't like the ":<<" in yaml files.

**Comment by stevoyoung** [comment]
I have 1.6.2 installed.

**Comment by fortuity** [comment]
0n 2011-3-27 I removed the workaround added to resolve Issue 17. There should now be no problem using any Rubygems version newer than 1.53 (2011-02-26).

I'm sorry the workaround bit you. Thanks for reporting it!

-- Daniel

**Comment by stevoyoung** [comment]
Thanks, Daniel - I'll check it out. Great work on the bundle, BTW.

**Comment by fortuity** [comment]
Thanks, it's a pleasure working on a project that gets a lot of love :-)

--- Daniel
