### ISSUE TITLE
Registration doesn't work in the demo app

### ISSUE THREAD

**Issue by lfborjas** [fortuity/rails3-mongoid-devise#3]
While the model has the `name` field, the view uses the default registration view of the devise gem. So no name field is shown and it raises a validation error.

I fixed it by overriding the template in my own views directory and adding the name field.

**Comment by fortuity** [comment]
Luis,

Thanks for catching this oversight. I've updated the tutorial and app to include customized views for user registration.

-- Daniel

**Comment by lfborjas** [comment]
You're welcome, your tutorial is pretty useful, I'm glad to find projects like this, sometimes useful stuff for rails or other frameworks is not used because rookies -like myself- don't know how to begin using it and nobody documents it.

**Comment by fortuity** [comment]
Thank you for the praise. And thank you making your contribution!
-- Daniel
