### ISSUE TITLE
Problem with Haml

### ISSUE THREAD

**Issue by natemartinsf** [fortuity/rails3-mongoid-devise#4]
I had to add this gem:

gem "haml-rails"

To the gemfile to get the haml generation to work correctly.

**Comment by fortuity** [comment]
I hadn't seen that rails3-generators was replaced with the haml-rails gem. Thanks for informing me. I've updated the app.

-- Daniel

**Comment by natemartinsf** [comment]
No problem, thanks for the great starter app!
