### ISSUE TITLE
Link to devise wiki in tutorial is incorrect

### ISSUE THREAD

**Issue by carols10cents** [fortuity/rails3-mongoid-devise#8]
In the tutorial under the "Add Devise Navigation Links" section, the link to the devise wiki is to:

http://wiki.github.com/plataformatec/devise/adding-menu-items-with-devise-actions-to-your-layout-template

which no longer seems to exist. The current page that looks like what that section covers is at:

https://github.com/plataformatec/devise/wiki/How-To:-Add-sign_in,-sign_out,-and-sign_up-links-to-your-layout-template

Thank you for the tutorial! It was very comprehensive and easy to follow, and this is the only issue I had.

**Comment by fortuity** [comment]
Thanks! I've updated the wiki. I'm glad the tutorial was useful for you.

-- Daniel
