### ISSUE TITLE
Devise Navigation Links

### ISSUE THREAD

**Issue by CoryFoy** [fortuity/rails3-mongoid-devise#9]
First, thanks a ton for the tutorial. It's awesome!

This is a minor nitpick - but in the section titled "Add Devise Navigation Links" the follower creates files in directories which don't exist yet, and then in the next step, they run the devise:views generator which creates at least the devise subdirectory. 

Suggestion (if this makes sense):

1) Move the devise:generate above the Add Devise Navigation Links section
2) Put in a statement that they'll have to create the directory (even though I knew to, I was afraid I had missed a step when it didn't exist)

Also, when editing the application.html.erb in the same section, the tutorial has the follower edit the file, create a css, and then go back and edit the file again using inline styles. This is a very minor nitpick, but maybe have them move the styles for the notice and alert to the css file while they are in there?

Other than that, awesome job! I'd be happy to fork and make the changes, but I don't know how to fork the Wiki to do a pull request, so if you know how to make that happen, let me know and I'll do that instead.

Thanks!

**Comment by fortuity** [comment]
Thanks for contributing! I'd be delighted if you can make these improvements.

You can edit the wiki directly (it's a wiki).

-- Daniel

**Comment by CoryFoy** [comment]
Done! I submitted the changes. Thanks again for a great tutorial!

**Comment by fortuity** [comment]
Thank you again. I appreciate your effort to improve clarity for others. I've added you to the contributor's list.
